### ISSUE TITLE
Add black as require dependency

### ISSUE THREAD

**Issue by DaniruKun** [mingrammer/diagrams#274]
It is not mentioned that the `black` autoformatter is required as a dependency.

**Comment by mingrammer** [comment]
`black` is only for development, and there are already dev dependencies in pyproject.toml.

```toml
[tool.poetry.dev-dependencies]
pytest = "^3.0"
pylint = "^2.4"
black = {version = "^19.0", allow-prereleases = true}
rope = "^0.14.0"
isort = "^4.3"
```
